language: ruby
sudo: false
cache: bundler
rvm:
  - 3.0
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
  - jruby-9.2.7.0
  - jruby-9.1.17.0
env:
  global:
    - COVERAGE=1
    - JRUBY_OPTS=''
    - RUBYOPT='-W0'
  matrix:
    - RESQUE='master'
    - RESQUE='~> 2.0.0'
    - RESQUE='~> 1.27'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.7.0
    - rvm: jruby-9.1.17.0
services:
  - redis-server
before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379
script:
  - bundle exec rake
  - bin/bundle_console_test.sh
addons:
  apt:
    packages:
      - redis-server
deploy:
  provider: rubygems
  api_key:
    secure: dM97lL/jTu14mEHD2Ih/vQfZ8cWJWb+DQ8UKZjkD2JfYtvwEAlkPG9RrrDkSHb5qkYxG2VAhjyx/0MZJ0TsVL6wrLMC9gcJb3yomw2Sch2Noj68tEndiSUHnxrB9gKzbhHbjLQXDqYf4Hco9/PHHQp4piFPJhLzNZRehIuTJPcA=
  gem: resque-scheduler
  on:
    tags: true
    repo: resque/resque-scheduler
    rvm: 2.4.2
    all_branches: true
