language: ruby
sudo: false
rvm:
- 1.9.3
# temporarily test on these 2.1.x patch releases to see when the pid file
# cleanup started breaking
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
- 2.1.4
- 2.1.5
- jruby-19mode
- rbx
env:
  global:
  - RESQUE_SCHEDULER_DISABLE_TEST_REDIS_SERVER=1
  - JRUBY_OPTS='-Xcext.enabled=true'
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: rbx
services:
- redis-server
notifications:
  email:
    recipients:
    - daniel.buch+resque-scheduler@gmail.com
deploy:
  provider: rubygems
  api_key:
    secure: dM97lL/jTu14mEHD2Ih/vQfZ8cWJWb+DQ8UKZjkD2JfYtvwEAlkPG9RrrDkSHb5qkYxG2VAhjyx/0MZJ0TsVL6wrLMC9gcJb3yomw2Sch2Noj68tEndiSUHnxrB9gKzbhHbjLQXDqYf4Hco9/PHHQp4piFPJhLzNZRehIuTJPcA=
  gem: resque-scheduler
  on:
    tags: true
    repo: resque/resque-scheduler
    rvm: '2.1'
