cache:
- vendor/bundle

environment:
  RUBYOPT: '-W0'
  COVERAGE: 1
  JRUBY_OPTS: ''
  TZ: 'UTC'

install:
- set PATH=C:\Ruby23\bin;%PATH%
- nuget install redis-64 -excludeversion
- redis-64\tools\redis-server.exe --service-install
- redis-64\tools\redis-server.exe --service-start
- bundle config --local path vendor/bundle
- bundle install

build: off

before_test:
- ruby -v
- gem -v
- bundle -v

test_script:
- bundle exec rake
- bin\bundle_console_test.bat
